apiVersion: v1
kind: Secret
metadata:
  name: idm-ldap
  namespace: group-sync-operator
type: Opaque
data:
  password: cmVkaGF0MTIzNA==
  username: dWlkPXNlcnZpY2VhY2NvdW50LGNuPXVzZXJzLGNuPWFjY291bnRzLGRjPWNvdHRvbixkYz1ibHVl


#  echo -n "uid=serviceaccount,cn=users,cn=accounts,dc=cotton,dc=blue" | base64 -w 0
